apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wikijs
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: wikijs-values
    env: wikijs.env
