apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-values-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.infrastructure:8200" # optional, the address of the Vault service, default values is https://vault:8200
    vault.security.banzaicloud.io/vault-role: "default" # optional, the default value is the name of the ServiceAccount the Pod runs in, in case of Secrets and ConfigMaps it is "default"
    vault.security.banzaicloud.io/vault-skip-verify: "false" # optional, skip TLS verification of the Vault server certificate
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls" # optional, the name of the Secret where the Vault CA cert is, if not defined it is not mounted
    vault.security.banzaicloud.io/vault-agent: "true" # optional, if true, a Vault Agent will be started to do Vault authentication, by default not needed and vault-env will do Kubernetes Service Account based Vault authentication
    vault.security.banzaicloud.io/vault-path: "kubernetes" # optional, the Kubernetes Auth mount path in Vault the default value is "kubernetes"
data:
  values.yaml: |
    postgresql:
      password: vault:secret/data/infrastructure/postgres#password
      repmgrPassword: vault:secret/data/infrastructure/postgres#repmgrpassword
      adminPassword: vault:secret/data/infrastructure/postgres#adminpassword
