apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
spec:
  releaseName: postgres
  chart:
    spec:
      chart: postgresql-ha
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "8.5.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: postgres-values
