postgresql:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
  password: vault:secret/data/infrastructure/postgres#password
  repmgrPassword: vault:secret/data/infrastructure/postgres#repmgrpassword

pgpool:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
  adminPassword: vault:secret/data/infrastructure/postgres#adminpassword

persistence:
  size: 10Gi
