global:
  postgresql:
    existingSecret: postgres-postgresql-ha-postgresql
    password: vault:secret/data/infrastructure/postgres#password
    repmgrPassword: vault:secret/data/infrastructure/postgres#repmgrpassword
  pgpool:
    existingSecret: postgres-postgresql-ha-pgpool
    adminPassword: vault:secret/data/infrastructure/postgres#adminpassword

postgresql:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls

pgpool:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls

persistence:
  size: 10Gi
