serviceAccount:
  create: true
  name: postgres

auth:
  username: vault:secret/data/infrastructure/postgres/credentials#username
  password: vault:secret/data/infrastructure/postgres/credentials#password

primary:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-role: postgres
  resources:
    limits:
      cpu: 125m
      memory: 256Mi
  persistence:
    size: 10Gi

readReplicas:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-role: postgres
  replicaCount: 1
  resources:
    limits:
      cpu: 125m
      memory: 256Mi
  persistence:
    size: 10Gi
