apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - secret.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - poddisruptionbudget.yaml
  - mutatingwebhookconfiguration.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: vault-secrets-webhook-env
    namespace: infrastructure
    env: configuration/secrets-webhook.env
