apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-cainjector-leader-election
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cainjector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-cainjector-leader-election
subjects:
  - kind: ServiceAccount
    name: cert-manager-cainjector