apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cainjector
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cainjector
automountServiceAccountToken: true