apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: teslamate
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: teslamate
      labels:
        app.kubernetes.io/name: teslamate
        app.kubernetes.io/version: 1.26.1
        app.kubernetes.io/part-of: teslamate
        app.kubernetes.io/component: teslamate
    spec:
      serviceAccountName: teslamate
      containers:
        - name: teslamate
          image: teslamate/teslamate:1.26.1
          envFrom:
            - configMapRef:
                name: teslamate-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 4000
          resources:
            requests:
              cpu: 8m
              memory: 256Mi
            limits:
              cpu: 16m
              memory: 384Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: teslamate-grafana
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: teslamate
      labels:
        app.kubernetes.io/name: teslamate-grafana
        app.kubernetes.io/version: 1.26.1
        app.kubernetes.io/part-of: teslamate
        app.kubernetes.io/component: grafana
    spec:
      serviceAccountName: teslamate
      securityContext:
        runAsUser: 472
        runAsGroup: 0
        fsGroup: 0
      volumes:
        - name: data-teslamate-grafana
          persistentVolumeClaim:
            claimName: data-teslamate-grafana
      containers:
        - name: teslamate-grafana
          image: teslamate/grafana:1.26.1
          envFrom:
            - configMapRef:
                name: teslamate-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              name: data-teslamate-grafana
          resources:
            requests:
              cpu: 4m
              memory: 32Mi
            limits:
              cpu: 8m
              memory: 64Mi
