apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
spec:
  releaseName: teslamate
  chart:
    spec:
      chart: teslamate
      sourceRef:
        kind: HelmRepository
        namespace: infrastructure
        name: leuchtturm-io
      version: 0.1.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
