apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: teslamate
resources:
  - serviceaccount.yaml
  - persistentvolumeclaim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: teslamate-env
    env: teslamate.env
