apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-teslamate-grafana
  labels:
    app.kubernetes.io/name: teslamate-grafana
    app.kubernetes.io/version: 1.26.1
    app.kubernetes.io/part-of: teslamate
    app.kubernetes.io/component: grafana
spec:
  storageClassName: scw-bssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
