apiVersion: v1
kind: Service
metadata:
  name: teslamate
spec:
  selector:
    app: teslamate
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: teslamate-grafana
spec:
  selector:
    app: teslamate-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
