apiVersion: v1
kind: Service
metadata:
  name: teslamate
spec:
  selector:
    app.kubernetes.io/name: teslamate
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: teslamate-grafana
spec:
  selector:
    app.kubernetes.io/name: teslamate
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
