apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: grafana-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: grafana-datasource
    options:
      disableNameSuffixHash: true
    files: 
      - datasource.yaml
configurations:
  - kustomizeconfig.yaml