apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-values
    files:
      - values.yaml=values.yaml
secretGenerator:
  - name: grafana-datasource
    files: 
      - datasource.yaml