serviceAccount:
  create: false
  name: grafana

admin:
  password: vault:secret/data/infrastructure/grafana/credentials#admin_password

grafana:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: https://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    vault.security.banzaicloud.io/vault-role: grafana
