apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-9.0.7
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-9.0.7
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
  annotations:
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/component: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql
      
