apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: nginx-ingress-controller-values
    namespace: infrastructure
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
