apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: caddy
        app.kubernetes.io/version: 2.5.1
        app.kubernetes.io/part-of: caddy
        app.kubernetes.io/component: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.5.1
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy
          resources:
            requests:
              cpu: 1m
              memory: 24Mi
            limits:
              cpu: 4m
              memory: 48Mi
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
