apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: caddy
        app.kubernetes.io/instance: medium-place-caddy
        app.kubernetes.io/version: 2.5.1
    spec:
      containers:
      - name: caddy
        image: caddy:2.5.1
        ports:
          - name: http
            protocol: TCP
            targetPort: 80
            containerPort: 80
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy
      volumes:
        - name: caddy-config
          configMap: 
            name: caddy-config