apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:2.5.1
        volumeMounts:
        - name: caddy-config
          mountPath: /etc/caddy
      volumes:
        - name: caddy-config
          configMap: 
            name: caddy-config