apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: caddy
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: caddy-config
    files:
      - configuration/Caddyfile
