apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    vault_cr: vault
spec:
  size: 2
  image: vault:1.6.2

  serviceAccount: vault

  serviceType: ClusterIP

  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  caNamespaces:
    - "*"

  unsealConfig:
    options:
      storeRootToken: true
    kubernetes:
      secretNamespace: infrastructure

  config:
    storage:
      raft:
        path: /vault/file
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: https://vault.infrastructure:8200
    cluster_addr: https://${.Env.POD_NAME}:8201
    ui: true

  serviceRegistrationEnabled: true

  resources:
    vault:
      limits:
        memory: 512Mi
        cpu: 100m
      requests:
        memory: 128Mi
        cpu: 75m

  externalConfig:
    policies:
      - name: allow_secrets
        rules: path "secret/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_pki
        rules: path "pki/*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: allow_all
        rules: path "*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["*"]
            policies: allow_secrets
            ttl: 1h
          - name: pki
            bound_service_account_names: ["vault-issuer"]
            bound_service_account_namespaces: ["infrastructure"]
            policies: allow_pki
            ttl: 1h

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
      - type: pki
        description: Vault PKI Backend
        config:
          default_lease_ttl: 168h
          max_lease_ttl: 720h
        configuration:
          config:
          - name: urls
            issuing_certificates: https://vault.infrastructure:8200/v1/pki/ca
            crl_distribution_points: https://vault.infrastructure:8200/v1/pki/crl
          root/generate:
          - name: internal
            common_name: vault.infrastructure
          roles:
          - name: default
            allowed_domains: localhost,pod,svc,default
            allow_subdomains: true
            generate_lease: true
            ttl: 1m
