apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
  labels:
    helm.sh/chart: vault-operator-1.15.2
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/managed-by: Helm
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-operator
        app.kubernetes.io/instance: vault-operator
    spec:
      containers:
        - name: vault-operator
          image: "ghcr.io/banzaicloud/vault-operator:1.15.0"
          imagePullPolicy: IfNotPresent
          command:
            - vault-operator
            - -sync_period
            - 1m
          env:
            - name: WATCH_NAMESPACE
              value:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: vault-operator
            - name: OPERATOR_LOG_LEVEL
              value: debug
            - name: BANK_VAULTS_IMAGE
              value: "ghcr.io/banzaicloud/bank-vaults:1.15.0"
          ports:
          - containerPort: 8080
          - containerPort: 8383
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: "/ready"
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      affinity:
        {}
      serviceAccountName: vault-operator
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-webhook
  labels:
    helm.sh/chart: vault-secrets-webhook-1.15.5
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/instance: vault-secrets-webhook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mutating-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-secrets-webhook
      app.kubernetes.io/instance: vault-secrets-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-secrets-webhook
        app.kubernetes.io/instance: vault-secrets-webhook
        security.banzaicloud.io/mutate: skip
      annotations:
        checksum/config: 62f961914e4bdbe4c746ab7827bc434066bb8b7233ea92b3602da89fcee14370
    spec:
      serviceAccountName: vault-secrets-webhook
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: vault-secrets-webhook-webhook-tls
      containers:
        - name: vault-secrets-webhook
          image: "ghcr.io/banzaicloud/vault-secrets-webhook:1.15.0"
          env:
            - name: TLS_CERT_FILE
              value: /var/serving-cert/tls.crt
            - name: TLS_PRIVATE_KEY_FILE
              value: /var/serving-cert/tls.key
            - name: LISTEN_ADDRESS
              value: ":8443"
            - name: VAULT_ENV_IMAGE
              value: "ghcr.io/banzaicloud/vault-env:1.15.0"
            - name: VAULT_IMAGE
              value: "vault:1.6.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 8443
          volumeMounts:
            - mountPath: /var/serving-cert
              name: serving-cert
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 65534
          resources:
            {}
