apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-operator
  namespace: infrastructure
spec:
  releaseName: vault-operator
  chart:
    spec:
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
      version: "1.15.6"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vault-operator-values
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: infrastructure
spec:
  releaseName: vault-secrets-webhook
  chart:
    spec:
      chart: vault-secrets-webhook
      sourceRef:
        kind: HelmRepository
        name: banzaicloud
      version: "1.15.8"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vault-secrets-webhook-values
