apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - namespace.yaml
  - crd.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - clusterrolebinding.yaml
  - persistentvolumeclaim.yaml
  - release.yaml
configMapGenerator:
  - name: vault-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
