apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - cr.yaml
  - hr.yaml
configMapGenerator:
  - name: vault-operator-values
    files:
      - vault-operator-values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
