
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vault-secrets-webhook
webhooks:
- name: pods.vault-secrets-webhook.admission.banzaicloud.com
  admissionReviewVersions: ["v1beta1"]
  clientConfig:
    service:
      name: vault-secrets-webhook
      path: /pods
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRY3E5eHlrckxCSkhXWmVwUHRHdExwREFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEl5TURJeE56SXdNakl6TjFvWERUTXlNREl4TlRJdwpNakl6TjFvd0ZURVRNQkVHQTFVRUF4TUtjM1pqTFdOaGRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTFdpbndaVmJzQ1Q2bHdoMUdaR1RwL011M0JHUVI0R3lPSEs0aVFpMTVaNVVvY08KdE5hcThDTkpJUnVvSXJLenJaMVlVZnhyRkwyRDlaeWUwSmtzekRjWWtrbTVZYTJmeWRER3B2d3l3TmViTUFIZgo0KysyaGdNcUFkU0JtQk1DRDNGWTR4TkVvbzc0dDEwaG5zMXBEQmc2Vkg1bEwyTVRjTC91Y0RmRVRaUk9yOVhSCjZpM242Q2kwWHlZTnV2WTFkU2hpNkVOSnJreVU3N3hhb2dZemRuNkpCQWY0ek90V29JbGJCYkRmV2VLb0pxV00KejJrMFBaazY3UGR1YituWjFHRE1neFdFdGtvMmc5eE11b0ZuN2dTMlozWXY1QmJ4enZTcVJCMS9QZTFBS1lIaQpDTE92emgxV0lUbGRZSFpUWnBQbHhid3I1NThNbFl5L2cyUXZmOXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlJ5VXpuVXUydHdVMFBMYnpHNkw0WUk1UDlTcXpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFpQkRoY0h2Mm1wUlN1VUFYdlc3a0JNaGEvUE5LMGhGcno0NGpaaFJoMlJwdkkvNks2RDYzCjhhOTFwbUpXS0kzK1IyTDY5ZjFKV0QzWS9BRThwNnFubHQxMUdTWW9qN0Zwc2Y5Vzcrc0xmZ0ZETi9Icmo5UTEKWFVpZHJoQWxIaE44bjZPbUJmdnVJcFM1TmtmV3cxR3Y0ZCtrVlhDazZCWnFmbWRHa1dUUUlyVlVwQ2t6Ky93dgppcXJ4VWNJTWUrY0pzcXBZR1RlQmp6aWc5Z0xNaW1ORDNpVXBwL21DTTFLL0Nyc2pzMFVwZTF3SnFFY0dRMTNBCklZTytVdlBZa29SOEpYQkpKWVNzS3QwT21sVllVSGVqNzJDZTFEVFI0VmlZb21HNEVMZXQrR3Z3U05EWEIrK3QKZXpReG9BVWxzSDROMGdXbDBoTTZWWjJxN1kxQytmZlkzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations:
    - CREATE
    apiGroups:
    - "*"
    apiVersions:
    - "*"
    resources:
    - pods
  failurePolicy: Ignore
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - kube-system
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
    - key: name
      operator: NotIn
      values:
      - default
  objectSelector:
    matchExpressions:
    - key: security.banzaicloud.io/mutate
      operator: NotIn
      values:
      - skip
  sideEffects: NoneOnDryRun
- name: secrets.vault-secrets-webhook.admission.banzaicloud.com
  admissionReviewVersions: ["v1beta1"]
  clientConfig:
    service:
      name: vault-secrets-webhook
      path: /secrets
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lRY3E5eHlrckxCSkhXWmVwUHRHdExwREFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEl5TURJeE56SXdNakl6TjFvWERUTXlNREl4TlRJdwpNakl6TjFvd0ZURVRNQkVHQTFVRUF4TUtjM1pqTFdOaGRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTFdpbndaVmJzQ1Q2bHdoMUdaR1RwL011M0JHUVI0R3lPSEs0aVFpMTVaNVVvY08KdE5hcThDTkpJUnVvSXJLenJaMVlVZnhyRkwyRDlaeWUwSmtzekRjWWtrbTVZYTJmeWRER3B2d3l3TmViTUFIZgo0KysyaGdNcUFkU0JtQk1DRDNGWTR4TkVvbzc0dDEwaG5zMXBEQmc2Vkg1bEwyTVRjTC91Y0RmRVRaUk9yOVhSCjZpM242Q2kwWHlZTnV2WTFkU2hpNkVOSnJreVU3N3hhb2dZemRuNkpCQWY0ek90V29JbGJCYkRmV2VLb0pxV00KejJrMFBaazY3UGR1YituWjFHRE1neFdFdGtvMmc5eE11b0ZuN2dTMlozWXY1QmJ4enZTcVJCMS9QZTFBS1lIaQpDTE92emgxV0lUbGRZSFpUWnBQbHhid3I1NThNbFl5L2cyUXZmOXNDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQjBHQTFVZERnUVdCQlJ5VXpuVXUydHdVMFBMYnpHNkw0WUk1UDlTcXpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFpQkRoY0h2Mm1wUlN1VUFYdlc3a0JNaGEvUE5LMGhGcno0NGpaaFJoMlJwdkkvNks2RDYzCjhhOTFwbUpXS0kzK1IyTDY5ZjFKV0QzWS9BRThwNnFubHQxMUdTWW9qN0Zwc2Y5Vzcrc0xmZ0ZETi9Icmo5UTEKWFVpZHJoQWxIaE44bjZPbUJmdnVJcFM1TmtmV3cxR3Y0ZCtrVlhDazZCWnFmbWRHa1dUUUlyVlVwQ2t6Ky93dgppcXJ4VWNJTWUrY0pzcXBZR1RlQmp6aWc5Z0xNaW1ORDNpVXBwL21DTTFLL0Nyc2pzMFVwZTF3SnFFY0dRMTNBCklZTytVdlBZa29SOEpYQkpKWVNzS3QwT21sVllVSGVqNzJDZTFEVFI0VmlZb21HNEVMZXQrR3Z3U05EWEIrK3QKZXpReG9BVWxzSDROMGdXbDBoTTZWWjJxN1kxQytmZlkzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - "*"
    apiVersions:
    - "*"
    resources:
    - secrets
  failurePolicy: Ignore
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - kube-system
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
    - key: name
      operator: NotIn
      values:
      - default
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
    - key: security.banzaicloud.io/mutate
      operator: NotIn
      values:
      - skip
  sideEffects: NoneOnDryRun
