apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-secrets-webhook
  labels:
    helm.sh/chart: vault-secrets-webhook-1.15.5
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/instance: vault-secrets-webhook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mutating-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-secrets-webhook
      app.kubernetes.io/instance: vault-secrets-webhook
