apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      version: "0.19.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - configMapKeyRef:
        name: vault
        namespace: vault
        key: values.yaml
        optional: false
