apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator
  labels:
    helm.sh/chart: vault-operator-1.15.2
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-webhook
  labels:
    helm.sh/chart: vault-secrets-webhook-1.15.5
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/instance: vault-secrets-webhook
    app.kubernetes.io/managed-by: Helm
