server:
  ha:
    enabled: true
    replicas: 3

    apiAddr: null

    raft:
      enabled: false
      setNodeId: false
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
        }
        service_registration "kubernetes" {}

  dataStorage:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
