apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault
    vault_cr: vault
spec:
  size: 3
  image: vault:1.6.2

  serviceAccount: vault

  serviceType: ClusterIP

  volumeClaimTemplates:
    - metadata:
        name: data-vault
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi

  volumeMounts:
    - name: data-vault
      mountPath: /vault/file

  caNamespaces:
    - "*"

  unsealConfig:
    options:
      storeRootToken: true
    kubernetes:
      secretNamespace: infrastructure

  config:
    storage:
      raft:
        path: /vault/file
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_disable: true
    api_addr: http://vault.infrastructure:8200
    cluster_addr: https://${.Env.POD_NAME}:8201
    ui: true

  serviceRegistrationEnabled: true

  resources:
    vault:
      requests:
        cpu: 75m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi

  externalConfig:
    policies:
      - name: allow_all
        rules: path "*" {
          capabilities = ["create", "read", "update", "delete", "list"]
          }
      - name: cloudflare
        rules: path "secret/data/external/cloudflare" {
          capabilities = ["read", "list"]
          }
      - name: mail
        rules: path "secret/data/external/mail" {
          capabilities = ["read", "list"]
          }
      - name: minio
        rules: path "secret/data/infrastructure/minio/*" {
          capabilities = ["read", "list"]
          }
      - name: postgresql
        rules: path "secret/data/infrastructure/postgresql/*" {
          capabilities = ["read", "list"]
          }
          path "secret/data/+/+/database" {
          capabilities = ["read", "list"]
          }
      - name: redis
        rules: path "secret/data/infrastructure/redis/*" {
          capabilities = ["read", "list"]
          }
      - name: vaultwarden
        rules: path "secret/data/leuchtturm-io/vaultwarden/*" {
          capabilities = ["read", "list"]
          }
      - name: teslamate
        rules: path "secret/data/medium-place/teslamate/*" {
          capabilities = ["read", "list"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: ["default", "vault-secrets-webhook"]
            bound_service_account_namespaces: ["*"]
            policies: allow_secrets
            ttl: 1h
          - name: external-dns
            bound_service_account_names: ["external-dns"]
            bound_service_account_namespaces: ["infrastructure"]
            policies: cloudflare
            ttl: 1h         
          - name: minio
            bound_service_account_names: ["minio"]
            bound_service_account_namespaces: ["infrastructure"]
            policies: minio
            ttl: 1h
          - name: postgresql
            bound_service_account_names: ["postgresql"]
            bound_service_account_namespaces: ["infrastructure"]
            policies: postgresql
            ttl: 1h
          - name: redis
            bound_service_account_names: ["redis"]
            bound_service_account_namespaces: ["infrastructure"]
            policies: redis
            ttl: 1h
          - name: vaultwarden
            bound_service_account_names: ["vaultwarden"]
            bound_service_account_namespaces: ["leuchtturm-io"]
            policies: 
              - vaultwarden
              - mail
            ttl: 1h
          - name: teslamate
            bound_service_account_names: ["teslamate"]
            bound_service_account_namespaces: ["medium-place"]
            policies: teslamate
            ttl: 1h
      - type: github
        options:
          listing_visibility: "unauth"
        config:
          organization: leuchtturm-io
        map:
          users:
            cschmatzler: allow_all

    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
