apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: vaultwarden
      labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/version: 1.24.0
        app.kubernetes.io/part-of: vaultwarden
        app.kubernetes.io/component: vaultwarden
    spec:
      serviceAccountName: vaultwarden
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.24.0
          envFrom:
            - configMapRef:
                name: vaultwarden-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          resources:
            requests:
              cpu: 1m
              memory: 24Mi
            limits:
              cpu: 8m
              memory: 48Mi