apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vaultwarden
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: vaultwarden-env
    env: vaultwarden.env
