apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/part-of: vaultwarden
    app.kubernetes.io/component: vaultwarden
    app.kubernetes.io/version: 1.24.0