apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: mastodon
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/version: 3.5.2
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: mastodon
    spec:
      serviceAccountName: mastodon
      initContainers:
        - name: mastodon-migrations
          image: tootsuite/mastodon:v3.5.2
          command:
            - bundle
            - exec
            - rails db:migrate
          envFrom:
            - configMapRef:
                name: mastodon-env
      containers:
        - name: mastodon-web
          image: tootsuite/mastodon:v3.5.2
          command:
            - bundle
            - exec
            - rails s -p 3000
          envFrom:
            - configMapRef:
                name: mastodon-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
          resources:
            requests:
              cpu: 64m
              memory: 1Gi
            limits:
              cpu: 128m
              memory: 2Gi
        - name: mastodon-streaming
          image: tootsuite/mastodon:v3.5.2
          command:
            - node
            - ./streaming
          envFrom:
            - configMapRef:
                name: mastodon-env
          ports:
            - name: http-ws
              protocol: TCP
              containerPort: 4000
          resources:
            requests:
              cpu: 8m
              memory: 128Mi
            limits:
              cpu: 16m
              memory: 256Mi
        - name: mastodon-sidekiq
          image: tootsuite/mastodon:v3.5.2
          command:
            - bundle
            - exec
            - sidekiq
          envFrom:
            - configMapRef:
                name: mastodon-env
          resources:
            requests:
              cpu: 128m
              memory: 512Mi
            limits:
              cpu: 256m
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon-redis
        app.kubernetes.io/version: 7.0.0
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: redis
    spec:
      serviceAccountName: mastodon
      containers:
        - name: mastodon-redis
          image: redis:7.0.0
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          resources:
            requests:
              cpu: 8m
              memory: 16Mi
            limits:
              cpu: 16m
              memory: 32Mi