apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: caddy
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: mastodon-env
    env: configuration/mastodon.env