apiVersion: v1
kind: Service
metadata:
  name: mastodon-web
spec:
  selector:
    app: mastodon-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mastodon-streaming
spec:
  selector:
    app: mastodon-streaming
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000