apiVersion: v1
kind: Service
metadata:
  name: mastodon
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/version: 3.5.2
    app.kubernetes.io/part-of: mastodon
spec:
  selector:
    app.kubernetes.io/name: mastodon
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: http-ws
      protocol: TCP
      port: 4000
      targetPort: 4000
