# Vault image used in infrastructure/vault/vault.
- name:  vault
# ACME solver used in infrastructure/controller/deployment.
- name: bitnami/acmesolver
# Deployed in the cluster is an image we're building ourselves with the S3 storage provider.
# This makes sure we get updates for the upstream image.
- name: matrixdotorg/synapse
