apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: vault-operator-env
    namespace: infrastructure
    env: configuration/operator.env
