apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: flux-system
      version: "4.0.17"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort
