apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: webhook
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: webhook
    spec:
      serviceAccountName: cert-manager-webhook
      securityContext:
        fsGroup: 1001  
      containers:
        - name: cert-manager-webhook
          image: bitnami/cert-manager-webhook:1.8.0-debian-10-r21
          args:
            - --v=2
            - --secure-port=10250
            - --dynamic-serving-ca-secret-namespace=$(POD_NAMESPACE)
            - --dynamic-serving-ca-secret-name=cert-manager-webhook-ca
            - --dynamic-serving-dns-names=cert-manager-webhook,cert-manager-webhook.default,cert-manager-webhook.default.svc
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: https
              containerPort: 10250
          livenessProbe:
             httpGet:
               path: /livez
               scheme: HTTP
               port: 6080
             initialDelaySeconds: 60
             periodSeconds: 10
             timeoutSeconds: 1
             successThreshold: 1
             failureThreshold: 3
          readinessProbe:
             httpGet:
               path: /healthz
               port: 6080
               scheme: HTTP
             initialDelaySeconds: 5
             periodSeconds: 5
             timeoutSeconds: 1
             successThreshold: 1
             failureThreshold: 3