apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
