apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: webhook
automountServiceAccountToken: true