apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-vault-agent
  labels:
    app.kubernetes.io/name: synapse
    synapse.kubernetes.io/name: synapse-vault-agent
    branches: "true"
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "synapse"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }
    template_config {
      error_on_missing_key = true
    }
    template {
      contents = <<EOH
        {{- with secret "secret/data/medium-place/synapse/secret" }}
        {{ .Data.data.signing_key }}
        {{ end }}
      EOH
      destination = "/tmp/medium.place.signing.key"
    }