apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-config
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "synapse"
        }
      }
      sink "file" {
        config = {
          path = "/vault/.vault-token"
        }
      }
    }
    exit_after_auth = false
    template_config {
      error_on_missing_key = true
    }
    template {
      contents = "{{- with secret \"secret/medium-place/synapse/secret\" }}{{ .Data.data.signing_key }}{{ end }}"
      destination = "/vault/secrets/medium.place.signing.key"
    }
    template {
      contents = <<EOH
        server_name: medium.place

        listeners:
          - port: 8008
            tls: false
            type: http
            x_forwarded: true
            bind_addresses: ['0.0.0.0']

            resources:
              - names: [client, federation]
                compress: false

        database:
          name: psycopg2
          txn_limit: 10000
          args:
            {{- with secret "secret/medium-place/synapse/database" }}
            host: {{ .Data.data.host }}
            port: 5432
            user: {{ .Data.data.user }}
            password: {{ .Data.data.password }}
            database: {{ .Data.data.name }}
            cp_min: 5
            cp_max: 10
            {{ end }}

        media_store_path: /tmp
        media_storage_providers:
          - module: s3_storage_provider.S3StorageProviderBackend
            store_local: True
            store_remote: True
            store_synchronous: True
            config:
              {{- with secret "secret/medium-place/synapse/s3" }}
              bucket: {{ .Data.data.bucket }}
              region_name: {{ .Data.data.region }}
              endpoint_url: {{ .Data.data.endpoint }}
              access_key_id: {{ .Data.data.access_key }}
              secret_access_key: {{ .Data.data.secret_key }}
              {{ end }}

        {{- with secret "secret/medium-place/synapse/secret" }}
        enable_registration: true
        registration_requires_token: true
        registration_shared_secret: {{ .Data.data.registration_key }}
        macaroon_secret_key: {{ .Data.data.macaroon_key }}
        {{ end }}

        report_stats: true
      EOH
      destination = "/vault/secrets/homeserver.yaml"
    }