apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: synapse
        vault.security.banzaicloud.io/vault-agent: "true"
      labels:
        app: synapse
    spec:
      serviceAccountName: synapse
      containers:
        - name: synapse
          image: cschmatzler/synapse:v1.58.1
          envFrom:
            - configMapRef:
                name: synapse-env
          volumeMounts:
            - name: synapse-config
              mountPath: /data/config/homeserver.yaml
              subPath: homeserver.yaml
            - name: synapse-signing-key
              mountPath: /data/config/medium.place.signing.key
              subPath: medium.place.signing.key
      volumes:
        - name: synapse-config
          configMap:
            name: synapse-config
        - name: synapse-signing-key
          secret:
            secretName: synapse-signing-key
