apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: synapse
        vault.security.banzaicloud.io/vault-agent-configmap: synapse-config
      labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/version: 1.58.1
        app.kubernetes.io/part-of: synapse
        app.kubernetes.io/component: synapse
    spec:
      serviceAccountName: synapse
      containers:
        - name: synapse
          image: cschmatzler/synapse:v1.58.1
          envFrom:
            - configMapRef:
                name: synapse-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 8008
          resources:
            requests:
              cpu: 64m
              memory: 512Mi
            limits:
              cpu: 128m
              memory: 1Gi
