apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: synapse
        vault.security.banzaicloud.io/vault-agent-configmap: synapse-config
      labels:
        app: synapse
    spec:
      serviceAccountName: synapse
      containers:
        - name: synapse
          image: cschmatzler/synapse:v1.58.1
          envFrom:
            - configMapRef:
                name: synapse-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse-coturn
  template:
    metadata:
      labels:
        app: synapse-coturn
    spec:
      hostNetwork: true
      serviceAccountName: synapse
      containers:
        - name: synapse-coturn
          image: coturn/coturn:4.5.2
          args:
            - "--min-port=49160"
            - "--max-port=49170"