apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: synapse
        vault.security.banzaicloud.io/vault-agent-configmap: synapse-config
      labels:
        app.kubernetes.io/name: synapse
        app.kubernetes.io/instance: medium-place-synapse
        app.kubernetes.io/version: 1.58.1
    spec:
      serviceAccountName: synapse
      containers:
        - name: synapse
          image: cschmatzler/synapse:v1.58.1
          ports:
            - name: http
              protocol: TCP
              targetPort: 8008
              containerPort: 8008
          envFrom:
            - configMapRef:
                name: synapse-env
