apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: synapse
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: synapse-env
    env: configuration/synapse.env
  - name: synapse-config
    files:
      - configuration/config.hcl
configurations:
  - kustomizeconfig.yaml
