apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: synapse
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: synapse-env
    env: synapse.env