apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: synapse
resources:
  - serviceaccount.yaml
  - deployment.yaml
configMapGenerator:
  - name: synapse-env
    env: synapse.env
  - name: synapse-config
    files:
      - homeserver.yaml=homeserver.yaml
generatorOptions:
  annotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-role: synapse