apiVersion: v1
kind: ServiceAccount
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
    app.kubernetes.io/part-of: synapse
    app.kubernetes.io/component: synapse
    app.kubernetes.io/version: 1.59.0