apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mastodon-elasticsearch
  namespace: medium-place
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: search
    app.kubernetes.io/version: 1.26.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/part-of: mastodon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: search
        app.kubernetes.io/version: 1.26.1
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: elasticsearch
          image: bitnami/elasticsearch:8.2.0-debian-10-r12
          ports:
            - name: http
              protocol: TCP
              containerPort: 9200
          volumeMounts:
            - name: data
              mountPath: /bitnami/elasticsearch/data
          # resources:
          #   requests:
          #     cpu: 32m
          #     memory: 64Mi
          #   limits:
          #     cpu: 64m
          #     memory: 128Mi
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place
        labels:
          app.kubernetes.io/name: elasticsearch
          app.kubernetes.io/part-of: mastodon
          app.kubernetes.io/component: search
      spec:
        storageClassName: scw-bssd-retain
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        