apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: mediumplace
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    tls:
      - hosts:
          - podinfo.medium.place
        secretName: podinfo-medium-place-tls
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: podinfo.medium.place
          paths:
            - path: /
              pathType: ImplementationSpecific
