apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslamate
  namespace: medium-place
  labels:
    app.kubernetes.io/name: teslamate
    app.kubernetes.io/part-of: teslamate
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.26.1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: teslamate
      app.kubernetes.io/part-of: teslamate
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-role: teslamate
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.max_tags: 5
      labels:
        app.kubernetes.io/name: teslamate
        app.kubernetes.io/part-of: teslamate
        app.kubernetes.io/component: server
        app.kubernetes.io/version: 1.26.1
    spec:
      serviceAccountName: teslamate
      containers:
        - name: teslamate
          image: teslamate/teslamate:1.26.1
          envFrom:
            - configMapRef:
                name: teslamate-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 4000
          resources:
            requests:
              cpu: 8m
              memory: 256Mi
            limits:
              cpu: 256m
              memory: 384Mi