apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: medium-place
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 1.16.8
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
      app.kubernetes.io/part-of: gitea
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-role: gitea        
        diun.enable: "true"
        diun.regopt: docker.io
        diun.watch_repo: "true"
        diun.include_tags: "^\\d+\\.\\d+\\.\\d+$"
      labels:
        app.kubernetes.io/name: gitea
        app.kubernetes.io/part-of: gitea
        app.kubernetes.io/component: server
        app.kubernetes.io/version: 1.16.8
    spec:
      serviceAccountName: gitea
      containers:
        - name: gitea
          image: gitea/gitea:1.16.8
          envFrom:
            - configMapRef:
                name: gitea-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
            - name: ssh
              protocol: TCP
              containerPort: 22
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 32m
              memory: 384Mi
            limits:
              cpu: 256m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: medium-place
        labels:
          app.kubernetes.io/name: gitea
          app.kubernetes.io/part-of: gitea
          app.kubernetes.io/component: server
      spec:
        storageClassName: scw-bssd-retain
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        