apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: infrastructure
  labels: 
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: external-dns
    app.kubernetes.io/component: external-dns
    app.kubernetes.io/version: 0.11.1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app.kubernetes.io/name: external-dns
      app.kubernetes.io/component: external-dns
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: external-dns
        app.kubernetes.io/part-of: external-dns
        app.kubernetes.io/component: external-dns
        app.kubernetes.io/version: 0.11.1
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: bitnami/external-dns:0.11.1-debian-10-r1
          args:
            - --metrics-address=:7979
            - --log-level=info
            - --log-format=text
            - --policy=upsert-only
            - --provider=cloudflare
            - --registry=txt
            - --interval=1m
            - --source=service
            - --source=ingress
          envFrom:
            - configMapRef:
                name: external-dns-env
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          resources:
            requests:
              cpu: 4m
              memory: 64Mi
            limits:
              cpu: 8m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
