apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podsecuritypolicy.yaml
  - serviceaccount.yaml
secretGenerator:
  - name: kube-prometheus-alertmanager-config
    files:
      - configuration/alertmanager.yaml
