apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: outline
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: outline-values
    env: outline.env
