apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-issuers
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-issuers
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-clusterissuers
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-clusterissuers
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-certificates
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-certificates
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-orders
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-orders
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-challenges
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-challenges
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-ingress-shim
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-ingress-shim
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-controller-approve
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-controller-approve
subjects:
  - kind: ServiceAccount
    name: cert-manager-controller
    namespace: infrastructure
