apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-controller
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: cert-manager-controller
      securityContext:
        fsGroup: 1001
      containers:
        - name: cert-manager
          image: bitnami/cert-manager:1.8.0-debian-10-r21
          args:
            - --v=2
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --leader-election-namespace=kube-system
            - --acme-http01-solver-image=docker.io/bitnami/acmesolver:1.8.0-debian-10-r21
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              protocol: TCP
              containerPort: 9402