apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-controller
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: 1.8.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
  replicas: 1
  template:
    metadata:
      annotations:
        diun.enable: "true"
      labels:
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/part-of: cert-manager
        app.kubernetes.io/component: controller
        app.kubernetes.io/version: 1.8.0
    spec:
      serviceAccountName: cert-manager-controller
      containers:
        - name: controller
          image: bitnami/cert-manager:1.8.0-debian-10-r21
          args:
            - --v=2
            - --leader-election-namespace=kube-system
            - --cluster-resource-namespace=$(POD_NAMESPACE)
            - --acme-http01-solver-image=bitnami/acmesolver:1.8.0-debian-10-r21
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              protocol: TCP
              containerPort: 9402
          resources:
            requests:
              cpu: 8m
              memory: 128Mi
            limits:
              cpu: 64m
              memory: 192Mi
