apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-controller
  namespace: infrastructureww
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller