apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "35.2.0"
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
