apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "11.2.16"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: minio-values
