apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: minio-env
    namespace: infrastructure
    env: configuration/minio.env