apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/version: 2022.5.8