apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/version: 2022.5.8
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/component: minio
  replicas: 4
  serviceName: minio-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/part-of: minio
        app.kubernetes.io/component: minio
        app.kubernetes.io/version: 2022.5.8
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: minio
    spec:
      serviceAccountName: minio
      containers:
        - name: minio
          image: bitnami/minio:2022.5.8-debian-10-r0
          envFrom:
            - configMapRef:
                name: minio-env
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: http
              protocol: TCP
              containerPort: 9000
            - name: http-console
              protocol: TCP
              containerPort: 9001
          resources:
            requests: 
              cpu: 8m
              memory: 512Mi
            limits: 
              cpu: 16m
              memory: 768Mi
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: infrastructure
        labels:
          app.kubernetes.io/name: minio
          app.kubernetes.io/part-of: minio
          app.kubernetes.io/component: minio
          app.kubernetes.io/version: 2022.5.8
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
        storageClassName: scw-bssd-retain
