apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: leuchtturm-io-root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: leuchtturm-io-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: leuchtturm-io-ca
  secretName: leuchtturm-io-ca-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: leuchtturm-io-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: leuchtturm-io-ca
  namespace: cert-manager
spec:
  ca:
    secretName: leuchtturm-io-ca-root-secret
