apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
metadata:
  name: issuers
spec:
  dependsOn:
    - name: cert-manager
resources:
  - letsencrypt.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
