apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
metadata:
  name: cert-manager
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
