apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
name: cert-manager
namespace: cert-manager
resources:
  - namespace.yaml
  - release.yaml
  - issuers.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
