apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
metadata:
  name: cert-manager
resources:
  - namespace.yaml
  - release.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
metadata:
  name: issuers
spec:
  dependsOn:
    - name: cert-manager
resources:
  - letsencrypt.yaml
