apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
resources:
  - crd.yaml
  - rbac.yaml
  - hr.yaml
  - clusterissuer.yaml
patches:
  - path: ca-injector-patch.yaml
    target:
      kind: Deployment
      name: cert-manager-ca-injector
