apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-issuer
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-issuer-token
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token
