apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
spec:
  releaseName: kube-prometheus
  chart:
    spec:
      chart: kube-prometheus
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: "6.9.7"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3