apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgresql-backup
spec:
  storageClassName: scw-bssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
