serviceAccount:
  create: true
  enabled: true
  name: postgresql

persistence:
  storageClass: scw-bssd-retain
  size: 5Gi

postgresql:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
    vault.security.banzaicloud.io/vault-role: postgresql
  livenessProbe:
    enabled: false
  customLivenessProbe:
    exec:
      command:
        - bash
        - -ec
        - "pg_isready -h localhost -U postgres"
  readinessProbe:
    enabled: false
  customReadinessProbe:
    exec:
      command:
        - bash
        - -ec
        - "pg_isready -h localhost -U postgres"
  password: vault:secret/data/infrastructure/postgresql/authentication#postgres_password
  repmgrPassword: vault:secret/data/infrastructure/postgresql/authentication#repmgr_password
  maxConnections: 250

pgpool:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
    vault.security.banzaicloud.io/vault-role: postgresql
  adminPassword: vault:secret/data/infrastructure/postgresql/authentication#pgpool_password
  customUsers:
    usernames: ${vault:secret/data/leuchtturm-io/vaultwarden/postgresql#user};${vault:secret/data/medium-place/mastodon/postgresql#user};${vault:secret/data/medium-place/synapse/postgresql#user};${vault:secret/data/medium-place/teslamate/postgresql#user}
    passwords: ${vault:secret/data/leuchtturm-io/vaultwarden/postgresql#password};${vault:secret/data/medium-place/mastodon/postgresql#password};${vault:secret/data/medium-place/synapse/postgresql#password};${vault:secret/data/medium-place/teslamate/postgresql#password}
  numInitChildren: 64
  maxPool: 20
  childMaxConnections: 10
