serviceAccount:
  create: true
  enabled: true
  name: postgresql

persistence:
  size: 8Gi

postgresql:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-role: postgresql
  livenessProbe:
    enabled: false
  customLivenessProbe:
    exec:
      command:
        - bash
        - -ec
        - 'PGPASSWORD=${vault:secret/data/infrastructure/postgresql/authentication#postgres_password} psql -w -U postgres -h 127.0.0.1 -c "SELECT 1"'
  readinessProbe:
    enabled: false
  password: vault:secret/data/infrastructure/postgresql/authentication#postgres_password
  repmgrPassword: vault:secret/data/infrastructure/postgresql/authentication#repmgr_password

pgpool:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-role: postgresql
  adminPassword: vault:secret/data/infrastructure/postgresql/authentication#pgpool_password
  customUsers:
    usernames: ${vault:secret/data/leuchtturm-io/vaultwarden/database#user};${vault:secret/data/medium-place/wikijs/database#user};${vault:secret/data/medium-place/teslamate/database#user}
    passwords: ${vault:secret/data/leuchtturm-io/vaultwarden/database#password};${vault:secret/data/medium-place/wikijs/database#password};${vault:secret/data/medium-place/teslamate/database#password}