serviceAccount:
  create: true
  enabled: true
  name: postgresql

persistence:
  storageClass: scw-bssd-retain
  size: 5Gi

postgresql:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-role: postgresql
  livenessProbe:
    enabled: false
  customLivenessProbe:
    exec:
      command:
        - bash
        - -ec
        - 'pg_isready -h localhost -U postgres'
  readinessProbe:
    enabled: false
  customReadinessProbe:
    exec:
      command:
        - bash
        - -ec
        - 'pg_isready -h localhost -U postgres'
  password: vault:secret/data/infrastructure/postgresql/authentication#postgres_password
  repmgrPassword: vault:secret/data/infrastructure/postgresql/authentication#repmgr_password
  maxConnections: 250

pgpool:
  podAnnotations:
    vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
    vault.security.banzaicloud.io/vault-role: postgresql
  adminPassword: vault:secret/data/infrastructure/postgresql/authentication#pgpool_password
  customUsers:
    usernames: ${vault:secret/data/leuchtturm-io/vaultwarden/database#user};${vault:secret/data/medium-place/synapse/database#user};${vault:secret/data/medium-place/teslamate/database#user};${vault:secret/data/medium-place/wikijs/database#user}
    passwords: ${vault:secret/data/leuchtturm-io/vaultwarden/database#password};${vault:secret/data/medium-place/synapse/database#password};${vault:secret/data/medium-place/teslamate/database#password};${vault:secret/data/medium-place/wikijs/database#password}
  numInitChildren: 64
  maxPool: 10
  childMaxConnections: 10