apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mastodon
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: mastodon
    app.kubernetes.io/version: 3.5.2
configMapGenerator:
  - name: mastodon-env
    env: configuration/mastodon.env
