apiVersion: v1
kind: ServiceAccount
metadata:
  name: mastodon
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: mastodon
    app.kubernetes.io/version: 3.5.2
