apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
configMapGenerator:
  - name: kube-prometheus-blackbox-exporter-config
    files:
      - configuration/config.yaml
