apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: kv-store
    app.kubernetes.io/version: 7.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: mastodon
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-role: mastodon
        diun.enable: "true"
        diun.watch_repo: "true"
        diun.exclude_tags: "latest"
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: kv-store
        app.kubernetes.io/version: 7.0.0
    spec:
      serviceAccountName: mastodon-redis
      containers:
        - name: redis
          image: redis:7.0.0
          imagePullPolicy: Always
          command:
            - redis-server
          #  - --requirepass $(REDIS_PASSWORD)
          #envFrom:
          #  - configMapRef:
          #      name: mastodon-redis-env
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          resources:
            requests:
              cpu: 16m
              memory: 16Mi
            limits:
              cpu: 32m
              memory: 32Mi
