apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-redis
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: redis
    app.kubernetes.io/version: 7.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: redis
        app.kubernetes.io/version: 7.0.0
    spec:
      containers:
        - name: redis
          image: redis:7.0.0
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          resources:
            requests:
              cpu: 16m
              memory: 16Mi
            limits:
              cpu: 32m
              memory: 32Mi
