apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-redis
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: redis
    app.kubernetes.io/version: 7.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/component: redis
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.infrastructure:8200
        vault.security.banzaicloud.io/vault-role: mastodon
      labels:
        app.kubernetes.io/name: mastodon
        app.kubernetes.io/part-of: mastodon
        app.kubernetes.io/component: redis
        app.kubernetes.io/version: 7.0.0
    spec:
      serviceAccountName: mastodon-redis
      containers:
        - name: redis
          image: redis:7.0.0
          command:
            - redis-server
          #  - --requirepass $(REDIS_PASSWORD)
          #envFrom:
          #  - configMapRef:
          #      name: mastodon-redis-env
          ports:
            - name: redis
              protocol: TCP
              containerPort: 6379
          resources:
            requests:
              cpu: 16m
              memory: 16Mi
            limits:
              cpu: 32m
              memory: 32Mi
