apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: mastodon-redis-env
    namespace: medium-place
    env: configuration/mastodon-redis.env
