apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: kv-store
    app.kubernetes.io/component: server
    app.kubernetes.io/version: 7.0.0
configMapGenerator:
  - name: mastodon-redis-env
    namespace: medium-place
    env: configuration/mastodon-redis.env
