apiVersion: v1
kind: Service
metadata:
  name: mastodon-redis
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: redis
    app.kubernetes.io/version: 7.0.0
spec:
  selector:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis