apiVersion: v1
kind: ServiceAccount
metadata:
  name: mastodon-redis
  labels:
    app.kubernetes.io/name: mastodon
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: redis
    app.kubernetes.io/version: 7.0.0
