apiVersion: v1
kind: ServiceAccount
metadata:
  name: mastodon-redis
  namespace: medium-place
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: mastodon
    app.kubernetes.io/component: kv-store
    app.kubernetes.io/version: 7.0.0
